-- MySQL Script generated by MySQL Workbench
-- Wed May 26 11:02:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lernapp_SWPra
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lernapp_SWPra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lernapp_SWPra` DEFAULT CHARACTER SET utf8 ;
USE `lernapp_SWPra` ;

-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`lernvorlieben`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`lernvorlieben` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`lernvorlieben` (
  `id_lernvorlieben` INT NOT NULL,
  `tageszeit` INT NULL,
  `tage` INT NULL,
  `frequenz` INT NULL,
  `lernart` INT NULL,
  `gruppengroesse` INT NULL,
  `lernort` INT NULL,
  PRIMARY KEY (`id_lernvorlieben`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`profil` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`profil` (
  `id_profil` INT NOT NULL,
  `studiengang` VARCHAR(45) NULL,
  `abschluss` VARCHAR(45) NULL,
  `semester` INT NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  PRIMARY KEY (`id_profil`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_profil_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_profil_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`person` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`person` (
  `id_person` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `vorname` VARCHAR(45) NULL,
  `semester` INT NULL,
  `alter` INT NULL,
  `geschlecht` VARCHAR(45) NULL,
  `lerngruppe` VARCHAR(45) NULL,
  `google_user_id` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `profil_id_profil` INT NOT NULL,
  PRIMARY KEY (`id_person`, `profil_id_profil`),
  INDEX `fk_person_profil1_idx` (`profil_id_profil` ASC) VISIBLE,
  CONSTRAINT `fk_person_profil1`
    FOREIGN KEY (`profil_id_profil`)
    REFERENCES `lernapp_SWPra`.`profil` (`id_profil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`lernfaecher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`lernfaecher` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`lernfaecher` (
  `id_lernfaecher` INT NOT NULL,
  `bezeichnung` VARCHAR(45) NULL,
  PRIMARY KEY (`id_lernfaecher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`person_has_lernfaecher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`person_has_lernfaecher` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`person_has_lernfaecher` (
  `lernfaecher_id_lernfaecher` INT NOT NULL,
  `kenntnisstand` VARCHAR(45) NULL,
  PRIMARY KEY (`lernfaecher_id_lernfaecher`),
  INDEX `fk_person_has_courses_courses1_idx` (`lernfaecher_id_lernfaecher` ASC) VISIBLE,
  CONSTRAINT `fk_person_has_courses_courses1`
    FOREIGN KEY (`lernfaecher_id_lernfaecher`)
    REFERENCES `lernapp_SWPra`.`lernfaecher` (`id_lernfaecher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`lerngruppe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`lerngruppe` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`lerngruppe` (
  `id_lerngruppe` INT NOT NULL,
  `teilnehmer` VARCHAR(45) NULL,
  `profil_id_profil` INT NOT NULL,
  PRIMARY KEY (`id_lerngruppe`, `profil_id_profil`),
  INDEX `fk_lerngruppe_profil1_idx` (`profil_id_profil` ASC) VISIBLE,
  CONSTRAINT `fk_lerngruppe_profil1`
    FOREIGN KEY (`profil_id_profil`)
    REFERENCES `lernapp_SWPra`.`profil` (`id_profil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`profil_has_lernfaecher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`profil_has_lernfaecher` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`profil_has_lernfaecher` (
  `profil_id_profil` INT NOT NULL,
  `profil_lernvorlieben_id_lernvorlieben` INT NOT NULL,
  `lernfaecher_id_lernfaecher` INT NOT NULL,
  `kenntnisstand` VARCHAR(45) NULL,
  PRIMARY KEY (`profil_id_profil`, `profil_lernvorlieben_id_lernvorlieben`, `lernfaecher_id_lernfaecher`),
  INDEX `fk_profil_has_lernfaecher_lernfaecher1_idx` (`lernfaecher_id_lernfaecher` ASC) VISIBLE,
  INDEX `fk_profil_has_lernfaecher_profil1_idx` (`profil_id_profil` ASC, `profil_lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_profil_has_lernfaecher_profil1`
    FOREIGN KEY (`profil_id_profil` , `profil_lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`profil` (`id_profil` , `lernvorlieben_id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profil_has_lernfaecher_lernfaecher1`
    FOREIGN KEY (`lernfaecher_id_lernfaecher`)
    REFERENCES `lernapp_SWPra`.`lernfaecher` (`id_lernfaecher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`teilnahme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`teilnahme` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`teilnahme` (
  `person_id_person` INT NOT NULL,
  `person_profil_id_profil` INT NOT NULL,
  `lerngruppe_id_lerngruppe` INT NOT NULL,
  `lerngruppe_profil_id_profil` INT NOT NULL,
  `id_teilnahme` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`person_id_person`, `person_profil_id_profil`, `lerngruppe_id_lerngruppe`, `lerngruppe_profil_id_profil`, `id_teilnahme`),
  INDEX `fk_person_has_lerngruppe_lerngruppe1_idx` (`lerngruppe_id_lerngruppe` ASC, `lerngruppe_profil_id_profil` ASC) VISIBLE,
  INDEX `fk_person_has_lerngruppe_person1_idx` (`person_id_person` ASC, `person_profil_id_profil` ASC) VISIBLE,
  CONSTRAINT `fk_person_has_lerngruppe_person1`
    FOREIGN KEY (`person_id_person` , `person_profil_id_profil`)
    REFERENCES `lernapp_SWPra`.`person` (`id_person` , `profil_id_profil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_lerngruppe_lerngruppe1`
    FOREIGN KEY (`lerngruppe_id_lerngruppe` , `lerngruppe_profil_id_profil`)
    REFERENCES `lernapp_SWPra`.`lerngruppe` (`id_lerngruppe` , `profil_id_profil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`konversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`konversation` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`konversation` (
  `id_konversation` INT NOT NULL,
  PRIMARY KEY (`id_konversation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`nachricht`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`nachricht` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`nachricht` (
  `id_nachricht` INT NOT NULL,
  `nachricht_inhalt` VARCHAR(45) NULL,
  `person_id_person` INT NOT NULL,
  `person_profil_id_profil` INT NOT NULL,
  `konversation_id_konversation` INT NOT NULL,
  PRIMARY KEY (`id_nachricht`, `person_id_person`, `person_profil_id_profil`, `konversation_id_konversation`),
  INDEX `fk_nachricht_person1_idx` (`person_id_person` ASC, `person_profil_id_profil` ASC) VISIBLE,
  INDEX `fk_nachricht_konversation1_idx` (`konversation_id_konversation` ASC) VISIBLE,
  CONSTRAINT `fk_nachricht_person1`
    FOREIGN KEY (`person_id_person` , `person_profil_id_profil`)
    REFERENCES `lernapp_SWPra`.`person` (`id_person` , `profil_id_profil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nachricht_konversation1`
    FOREIGN KEY (`konversation_id_konversation`)
    REFERENCES `lernapp_SWPra`.`konversation` (`id_konversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`tage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`tage` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`tage` (
  `id_tage` INT NOT NULL,
  `präferenz` VARCHAR(45) NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  PRIMARY KEY (`id_tage`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_tage_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_tage_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`tageszeit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`tageszeit` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`tageszeit` (
  `id_tageszeit` INT NOT NULL,
  `präferenz` VARCHAR(45) NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  PRIMARY KEY (`id_tageszeit`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_tageszeit_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_tageszeit_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`frequenz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`frequenz` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`frequenz` (
  `id_frequenz` INT NOT NULL,
  `präferenz` VARCHAR(45) NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  PRIMARY KEY (`id_frequenz`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_frequenz_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_frequenz_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`lernart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`lernart` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`lernart` (
  `id_lernart` INT NOT NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  `präferenz` VARCHAR(45) NULL,
  PRIMARY KEY (`id_lernart`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_lernart_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_lernart_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`gruppengroesse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`gruppengroesse` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`gruppengroesse` (
  `id_gruppengroesse` INT NOT NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  `präferenz` VARCHAR(45) NULL,
  PRIMARY KEY (`id_gruppengroesse`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_gruppengroesse_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_gruppengroesse_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`lernort`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`lernort` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`lernort` (
  `id_lernort` INT NOT NULL,
  `lernvorlieben_id_lernvorlieben` INT NOT NULL,
  `präferenz` VARCHAR(45) NULL,
  PRIMARY KEY (`id_lernort`, `lernvorlieben_id_lernvorlieben`),
  INDEX `fk_lernort_lernvorlieben1_idx` (`lernvorlieben_id_lernvorlieben` ASC) VISIBLE,
  CONSTRAINT `fk_lernort_lernvorlieben1`
    FOREIGN KEY (`lernvorlieben_id_lernvorlieben`)
    REFERENCES `lernapp_SWPra`.`lernvorlieben` (`id_lernvorlieben`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`vorschlag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`vorschlag` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`vorschlag` (
  `id_vorschlag` INT NOT NULL,
  `person_id_person` INT NOT NULL,
  `id_match` INT NULL,
  PRIMARY KEY (`id_vorschlag`, `person_id_person`),
  INDEX `fk_vorschlag_person1_idx` (`person_id_person` ASC) VISIBLE,
  CONSTRAINT `fk_vorschlag_person1`
    FOREIGN KEY (`person_id_person`)
    REFERENCES `lernapp_SWPra`.`person` (`id_person`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lernapp_SWPra`.`teilnehmer_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lernapp_SWPra`.`teilnehmer_chat` ;

CREATE TABLE IF NOT EXISTS `lernapp_SWPra`.`teilnehmer_chat` (
  `id_teilnehmer_chat` INT NOT NULL,
  `person_id_person` INT NOT NULL,
  `person_profil_id_profil` INT NOT NULL,
  `konversation_id_konversation` INT NOT NULL,
  PRIMARY KEY (`id_teilnehmer_chat`, `person_id_person`, `person_profil_id_profil`, `konversation_id_konversation`),
  INDEX `fk_teilnehmer_chat_person1_idx` (`person_id_person` ASC, `person_profil_id_profil` ASC) VISIBLE,
  INDEX `fk_teilnehmer_chat_konversation1_idx` (`konversation_id_konversation` ASC) VISIBLE,
  CONSTRAINT `fk_teilnehmer_chat_person1`
    FOREIGN KEY (`person_id_person` , `person_profil_id_profil`)
    REFERENCES `lernapp_SWPra`.`person` (`id_person` , `profil_id_profil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teilnehmer_chat_konversation1`
    FOREIGN KEY (`konversation_id_konversation`)
    REFERENCES `lernapp_SWPra`.`konversation` (`id_konversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
